apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-model
  labels:
    app: heart-disease-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease-model
  template:
    metadata:
      labels:
        app: heart-disease-model
    spec:
      containers:
        - name: heart-disease-model
          image: us-central1-docker.pkg.dev/your-heart-disease-mlops/heart-disease-repo/heart-disease-model:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
